force-app/main/default/objects/Noright__c/Noright__c.object-meta.xml
<CustomObject>
    <label>Noright</label>
    <nameField>
        <label>Noright Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Noright</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Read__c/Read__c.object-meta.xml
<CustomObject>
    <label>Read</label>
    <nameField>
        <label>Read Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Read__c/fields/Noright__c.field-meta.xml
<CustomField>
    <fullName>Noright__c</fullName>
    <label>Noright</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Update__c/Update__c.object-meta.xml
<CustomObject>
    <label>Update</label>
    <nameField>
        <label>Update Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Update__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <label>Read</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerExtensionWithoutSharing.cls
public with sharing class  ControllerExtensionWithoutSharing {

    public List<Read__c> reads  {get;set;} 
    public List<update__c> updates  {get;set;} 
    public List<Noright__c> norights  {get;set;} 
    public List<update__c> fakenorights  {get;set;} 
    
    public ControllerExtensionWithoutSharing() {
        Reads= new List<SObject>();
        updates= new List<SObject>();
        norights= new List<SObject>();
        fakenorights= new List<SObject>();
        
    }
    
    
    public void readtest() {
        
        Map<string,List<Sobject>> datas=ModeUserSystem.readTest();
        
        norights= datas.get('Noright__c');
        fakenorights= new List<SObject>();
        for(noright__c n : norights)
        {
            fakenorights.add(new update__c( Name = n.Name ));
        }
        System.debug(norights);
        Reads=  datas.get('Read__c');
        updates=  datas.get('Update__c');

        
    }
    public void updateTest() {
        

        ModeUserSystem.updateTest();
        
    }
    public void deleteTest() {
        

        ModeUserSystem.deleteTest();
        
    }
    
    public void createTest() {
        

        ModeUserSystem.createTest();
        
    }
    
    read__c read;

    public ControllerExtensionWithoutSharing(ApexPages.StandardController stdController) {
        this.read = (read__c)stdController.getRecord();
    }
}